version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    working_directory: ~/rails-docker-yoshizawa/src
    steps:
      - checkout:
          path: ~/rails-docker-yoshizawa
      - ruby/install-deps  
  test:
    docker:
    - image: circleci/ruby:3.0.2
    - user: root
    - image: circleci/mysql:5.5
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: app_test
        MYSQL_USER: root
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: "127.0.0.1"
      RAILS_ENV: test
    working_directory: /src
    steps:
    - checkout:
        path: ~/rails-docker-yoshizawa
    - ruby/install-deps
    - run:
        name: Database setup
        command: bundle exec rails db:migrate
    - run:
        name: test
        command: bundle exec rake test

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
          - build
